### ISSUE TITLE
Lab Material drive link is not accessible

### ISSUE THREAD

**Issue by growupboron** [HiPeRT/F1tenth-RTES#1]
The drive link for Lab Material on the README is not accessible even from UNIMORE credentials.![image](https://user-images.githubusercontent.com/41593068/232836249-b5995c91-c03e-4375-9c0d-eac65026f36b.png)

**Comment by pburgio** [comment]
Thanks Boron!

**Comment by growupboron** [comment]
The password of the vbox image is: F1t3nth23
